apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "ff-common.fullname" . }}-zaakbrug-env
  labels:
    {{- include "ff-common.labels" . | nindent 4 }}
data:
  zaakbrug.zds.timezone: "{{ .Values.zaakbrug.zds.timezone | default "UTC" }}"
  {{- with .Values.frank.caCertificates.enabled }}
  USE_SYSTEM_CA_CERTS: "Yes Please"
  {{- end }}