{{/*
Create a ServiceAccount
*/}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "drill.serviceAccountName" . }}
  labels:
    {{- include "drill.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}