name: Update appVersion
on:
  workflow_dispatch:
    inputs:
      distinct_id:
      chart:
        required: true
        description: Path to chart to update
      appVersion:
        required: true
        description: The desired version


jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: echo distinct ID ${{ inputs.distinct_id }}
        run: echo ${{ inputs.distinct_id }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install PyBump
        run: pip install pybump
      - name: The chart ${{ inputs.chart }} will be updated to appVersion ${{ inputs.appVersion }} and automatically bumped
        run: echo The chart ${{ inputs.chart }} will be updated to appVersion ${{ inputs.appVersion }}
      - name: update appVersion
        run: pybump set --app-version --set-version ${{ inputs.appVersion }} --file ${{ inputs.chart }}/Chart.yaml
      - name: update version
        run: pybump bump --level patch --file charts/zaakbrug/Chart.yaml
      - uses: stefanzweifel/git-auto-commit-action@v4
